name: Validate with hassfest

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
  schedule:
    - cron: "30 7 1 * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master
