name: Validate

on:
  push:
    paths-ignore:
      - "README.md"
      - "info.md"
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Check PEP8
        uses: rahul-deepsource/pyaction
        with:
          python-root-list: "custom_components/"
          use-pycodestyle: true

      - name: HACS validation
        uses: hacs/action@main
        with:
          CATEGORY: integration

      - name: HASSFEST
        uses: home-assistant/actions/hassfest@master
